title: Code Camp 2021
tagline: Página de información del Code Camp 2021
description: >-
  Comparte | Aprende | Desarrolla
tags:
  - Code Camp 2021
  - Microsoft Dev Group Cobán
  - Azure
  - .NET Core
  - Kubernetes
  - DevOps
  - Machine Learning
  - Python
theme: jekyll-theme-cayman